// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using USTIT.Services.StudentAPI.Data;

#nullable disable

namespace USTIT.Services.StudentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230911071803_createStudentTable")]
    partial class createStudentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("USTIT.Services.StudentAPI.Models.Student", b =>
                {
                    b.Property<string>("FullStdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("CONVERT([nvarchar](50),(CONVERT([nvarchar](50),[AcYear],(0))+CONVERT([nvarchar](50),[DeptCode],(0)))+right('0000'+CONVERT([nvarchar](50),[StdNo],(0)),(4)),(0))", true);

                    b.Property<int>("AcYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StdNo")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("FullStdID");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
